# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "colorize", "~> 0.8.1"

gem 'tty-cursor'

gem 'tty-prompt'

gem 'artii'

gem 'test-unit'

gem 'io-console'
